### ISSUE TITLE
error traceback

### ISSUE THREAD

**Issue by spamito34** [DIGITALCRIMINAL/UltimaScraper#1393]
hello , i know shit about coding since month i use your app , thank you for that ; i trie to use the latest version but i got this

Traceback (most recent call last):
  File "C:\Users\heros\Downloads\OnlyFans-7.4\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\heros\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\heros\Downloads\OnlyFans-7.4\start_ofd.py", line 46, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\heros\Downloads\OnlyFans-7.4\datascraper\main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\heros\Downloads\OnlyFans-7.4\modules\onlyfans.py", line 115, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "C:\Users\heros\Downloads\OnlyFans-7.4\extras\OFLogin\start_ofl.py", line 87, in login
    email_input = web_browser.find_element_by_id("input-71")
  File "C:\Users\heros\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\heros\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\heros\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\heros\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="input-71"]

i have update the script , the setting but i dont know how to fix that bymself ,it hapend when the geocko browser open i enter my login , im logged and nothing happend except that in cmd im asking for some  help, have a nice day

**Comment by DIGITALCRIMINAL** [comment]
Delete config.json

**Comment by spamito34** [comment]
> Delete config.json

yes i have deleted but i'm still stuck when geogheko open , i'm logged and nothing happend

**Comment by juelsz** [comment]
I get this from start_ofd.py

Site: 0 = onlyfans |

Traceback (most recent call last):
  File "C:\Users\Alex\Desktop\OnlyFans-7.4\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Alex\Desktop\OnlyFans-7.4\start_ofd.py", line 43, in main
    x = int(x)
ValueError: invalid literal for int() with base 10: ''

**Comment by Cachencho1337** [comment]
i had the same one 

Traceback (most recent call last):
  File "D:\Documentos\OnlyFans-master\start_ofd.py", line 62, in <module>
    loop.run_until_complete(main())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Documentos\OnlyFans-master\start_ofd.py", line 43, in main
    x = int(x)
ValueError: invalid literal for int() with base 10: ''

**Comment by DIGITALCRIMINAL** [comment]
> > Delete config.json
> 
> yes i have deleted but i'm still stuck when geogheko open , i'm logged and nothing happend

nvm, login the alternative way, OF changed something.

**Comment by OrmazdFR** [comment]
Hi, just to say I fixed it by editing line 43 in start_ofd.py
`x = int(x)` becomes `x = int(0x0)`
