### ISSUE TITLE
Issue importing from sqlalchemy

### ISSUE THREAD

**Issue by MyPersonalKov** [DIGITALCRIMINAL/UltimaScraper#1422]
I recently pulled from master, and I've been having some issues running the app.

I'm getting:

```
Traceback (most recent call last):
  File "C:\Programs\Onlyfans\OnlyFans-repo\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Programs\Onlyfans\OnlyFans-repo\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Programs\Onlyfans\OnlyFans-repo\helpers\main_helper.py", line 1, in <module>
    from database.models.api_table import api_table
  File "C:\Programs\Onlyfans\OnlyFans-repo\database\models\api_table.py", line 7, in <module>
    from sqlalchemy.orm import declarative_base  # type: ignore
ImportError: cannot import name 'declarative_base' from 'sqlalchemy.orm' (C:\Users\Home\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\__init__.py)
```

I've run `pip install --upgrade --user -r requirements.txt`, and it says all dependencies are up-to-date.

I had updated my Python version to 3.9.5 recently, but it pulled the new dependencies just fine.  ~~I was previously having some issues with modules, but I was ultimately able to pull all the dependencies properly.~~

EDIT: The dependency update when I updated python versions seemingly worked, but it's still not able to import from sqlalchemy.

**Comment by MyPersonalKov** [comment]
Maybe related to #1420?
