### ISSUE TITLE
KeyError: 'user_id'

### ISSUE THREAD

**Issue by bobbydennett** [DIGITALCRIMINAL/UltimaScraper#1441]
Running on latest version from master branch, experiencing the following error:
```
OnlyFans on  master via 🐍 v3.9.5 (_MacEnv3.9.5) on ☁️  (us-east-1)
❯ ./start_ofd.py
Site: 0 = onlyfans |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = ...
1
Auth (V1) Attempt 1/10
Welcome ... | ...
Scraping Paid Content
...
100%|████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2033.11it/s]
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "/Volumes/T5_2TB/Git/GitHub/DIGITALCRIMINAL/OnlyFans/./start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Volumes/T5_2TB/Git/GitHub/DIGITALCRIMINAL/OnlyFans/./start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/Volumes/T5_2TB/Git/GitHub/DIGITALCRIMINAL/OnlyFans/datascraper/main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "/Volumes/T5_2TB/Git/GitHub/DIGITALCRIMINAL/OnlyFans/modules/onlyfans.py", line 409, in paid_content_scraper
    await process_metadata(
  File "/Volumes/T5_2TB/Git/GitHub/DIGITALCRIMINAL/OnlyFans/modules/onlyfans.py", line 659, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "/Volumes/T5_2TB/Git/GitHub/DIGITALCRIMINAL/OnlyFans/helpers/main_helper.py", line 559, in export_sqlite
    post_db.user_id = post["user_id"]
KeyError: 'user_id'
```

**Comment by DIGITALCRIMINAL** [comment]
Which model was it scraping

**Comment by bobbydennett** [comment]
Looks to be `funsizedasian`

**Comment by 365ks** [comment]
I'm having the same issue and I noticed if I don't transfer over the old .sites folder and start fresh the error disappears. Unfortunately this would mean it would redownload everything vs what is just new

**Comment by bobbydennett** [comment]
Yeah, I ended up just going with fresh "download" and "metadata" directories. Not ideal, but works. In any case, appreciate the effort of @DIGITALCRIMINAL and the comment, @365ks.
