### ISSUE TITLE
KeyError: 'user_id'

### ISSUE THREAD

**Issue by DarkDownloader** [DIGITALCRIMINAL/UltimaScraper#1460]
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome USERNAME
Scraping Paid Content
Scraping - sweetaries | 1 / 18
Scraping - hypedoutbabe | 2 / 18
Scraping - sexyfuckers808 | 3 / 18
Scraping - sophialane | 4 / 18
Scraping - fandy | 5 / 18
  0%|←[35m                                                                                            ←[0m| 0/3 [00:00<?100%|←[35m███████████████████████████████████████████████████████████████████████████████████←[0m| 3/3 [00:00<00:00, 856.91it/s]←[0m
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "C:\Users\D\Documents\GitHub\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\D\Documents\GitHub\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\D\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "C:\Users\D\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 411, in paid_content_scraper
    await process_metadata(
  File "C:\Users\D\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 661, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "C:\Users\D\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 568, in export_sqlite
    post_db.user_id = post["user_id"]
KeyError: 'user_id'

**Comment by DarkDownloader** [comment]
I just ran `pip install --upgrade --user -r requirements.txt` and it did update a couple things, however this error still persists.

**Comment by 365ks** [comment]
I'm having the same issue and I noticed if I don't transfer over the old .sites folder and start fresh the error disappears. Unfortunately this would mean it would redownload everything vs what is just new

**Comment by DarkDownloader** [comment]
Welcome d
Scraping Paid Content
Scraping - hagsxrlou | 1 / 15
100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 333.21it/s]
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content
Traceback (most recent call last):
  File "C:\Users\D\Documents\GitHub\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\D\Documents\GitHub\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\D\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "C:\Users\De\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 411, in paid_content_scraper
    await process_metadata(
  File "C:\Users\D\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 661, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "C:\Users\D\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 568, in export_sqlite
    post_db.user_id = post["user_id"]
KeyError: 'user_id'

**Comment by DarkDownloader** [comment]
> I'm having the same issue and I noticed if I don't transfer over the old .sites folder and start fresh the error disappears. Unfortunately this would mean it would redownload everything vs what is just new

I tried this but it actually didn't fix it for me.

**Comment by Muruxror** [comment]
Same here, 

allready did what @365ks said, didnt do noting for me. I deleted all the files (from the scraper not OF) and deleted the profile and created a new one and double-checked if anything changed, but I can't find anything.

**Comment by DarkDownloader** [comment]
This went from 'user_id' error to 'created_at'

Scraping Paid Content
Scraping - starrybunny | 1 / 12
Scraping - goodbrain2020 | 2 / 12
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 285.79it/s]
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "C:\Users\D\Documents\GitHub\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\D\Documents\GitHub\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\D\Documents\GitHub\OnlyFans\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "C:\Users\D\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 411, in paid_content_scraper
    await process_metadata(
  File "C:\Users\D\Documents\GitHub\OnlyFans\modules\onlyfans.py", line 661, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "C:\Users\D\Documents\GitHub\OnlyFans\helpers\main_helper.py", line 582, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'
