### ISSUE TITLE
KeyError: 'created_at'`

### ISSUE THREAD

**Issue by Gamma-Velorum** [DIGITALCRIMINAL/UltimaScraper#1483]
Using latest commit and on Python 3.9.6 with all updated requirements.

```
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content
Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Userrrrrrrrr\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "O:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "O:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 837, in prepare_scraper
    await process_metadata(
  File "O:\OnlyFans-master\modules\onlyfans.py", line 661, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "O:\OnlyFans-master\helpers\main_helper.py", line 582, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'

Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Userrrrrrrrr\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "O:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "O:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 837, in prepare_scraper
    await process_metadata(
  File "O:\OnlyFans-master\modules\onlyfans.py", line 661, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "O:\OnlyFans-master\helpers\main_helper.py", line 582, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'
```

**Comment by Gamma-Velorum** [comment]
Also getting this

```
Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Userrrrrrrrr\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "O:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "O:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 161, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 837, in prepare_scraper
    await process_metadata(
  File "O:\OnlyFans-master\modules\onlyfans.py", line 661, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "O:\OnlyFans-master\helpers\main_helper.py", line 582, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'
```

**Comment by valdearg** [comment]
Also getting this error.

```Scrape Processing
Name: freemikomihokina
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 398/398 [00:00<00:00, 1961.11it/s]
Processing metadata.
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Traceback (most recent call last):
  File "G:\Scripts\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\Scripts\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "G:\Scripts\OnlyFans\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 840, in prepare_scraper
    await process_metadata(
  File "G:\Scripts\OnlyFans\modules\onlyfans.py", line 664, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "G:\Scripts\OnlyFans\helpers\main_helper.py", line 582, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'```

It happens on multiple models. Free or paid.

**Comment by EightDee** [comment]
I keep getting this error too. It is failing on the same account

`Scrape Processing
Name: queenazita
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/3
Type: Archived Posts
Processing Scraped Posts
  0%|←[35m
100%|←[35m████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
.74it/s]←[0m
Processing metadata.
Merging new metadata with legacy metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 5493253cc03c, content
Traceback (most recent call last):
  File "Y:\Temp\Scrape\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\eight\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "Y:\Temp\Scrape\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "Y:\Temp\Scrape\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "Y:\Temp\Scrape\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 840, in prepare_scraper
    await process_metadata(
  File "Y:\Temp\Scrape\modules\onlyfans.py", line 664, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "Y:\Temp\Scrape\helpers\main_helper.py", line 582, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'`

**Comment by valdearg** [comment]
Printing out the `media` object gives some info.

Working:

```
{'media_id': 389561134, 'links': ['giant link here!'], 'media_type': 'Images', 'preview': False, 'created_at': '03-06-2020 14:41:49', 'directory': 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans-new2\\freemikomihokina\\Posts\\Images\\26501899 (03-06-2020)', 'filename': '1080x1920_7547c21f8b614b53bb8e927c8056bed8.jpg', 'linked': None}
```

Not working and it craps out:

```
{'version': 2, 'content': {'Images': {'valid': [], 'invalid': []}, 'Videos': {'valid': [], 'invalid': []}, 'Audios': {'valid': [], 'invalid': []}, 'Texts': {'valid': [], 'invalid': []}}, 'media_id': 126070141, 'links': ['giant link here!'], 'directory': 'G:\\Scripts\\OnlyFans\\.sites\\OnlyFans\\freemikomihokina\\Posts\\Images\\52574559 (25-09-2020)', 'filename': '1080x1440_aadfb3ff811d7ff5a2c88c9c3292a48e.jpg', 'size': 1, 'media_type': 'Images'}
```

**Comment by starrlord314** [comment]
Having a similar issue with the KeyError: created_at -- I switched my metadata and download directory and that "fixes" it but requires a full pull of the files, which isn't ideal. Any ideas?

**Comment by valdearg** [comment]
Not too sure, we're waiting on @DIGITALCRIMINAL really. Hopefully that info helps a little.

**Comment by valdearg** [comment]
I don't know if this will have further ramifications elsewhere, but if you change the line:

`                created_at = media["created_at"]`

On roughly line 582 to:

```
try:
    created_at = media["created_at"]
except:
    created_at = postedAt
```

At least it doesn't go absolutely insane? Happy for others better at python than I am to confirm!
