### ISSUE TITLE
TypeError: 'error_details' object is not subscriptable

### ISSUE THREAD

**Issue by avekifes** [DIGITALCRIMINAL/UltimaScraper#1494]
I'm running into the following error with the latest commits:

> Scrape Processing
Name: anneamor
Type: Profile
Type: Stories
Scrape Attempt: 1/100
Traceback (most recent call last):
File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 60, in
loop.run_until_complete(main())
File "C:\Users\username\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
return future.result()
File "C:\Users\username\Desktop\OnlyFans-master\start_ofd.py", line 44, in main
api = await main_datascraper.start_datascraper(
File "C:\Users\username\Desktop\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
await main_helper.process_names(
File "C:\Users\username\Desktop\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
result = await module.start_datascraper(authed, username, site_name)
File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 160, in start_datascraper
await prepare_scraper(authed, site_name, item)
File "C:\Users\username\Desktop\OnlyFans-master\modules\onlyfans.py", line 786, in prepare_scraper
highlight = await subscription.get_highlights(hightlight_id=highlight.id)
File "C:\Users\username\Desktop\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 273, in get_highlights
results = [create_story(x) for x in results["stories"]]
TypeError: 'error_details' object is not subscriptable

**Comment by WellSomething** [comment]
Have the same issue with a profile which gave me year long free trial or subscription.

**Comment by Gamma-Velorum** [comment]
`Scrape Processing
Name: kasia12345
Type: Profile
100%|██████████████████████████████████████████████████████████████████████████████| 1.18M/1.18M [00:04<00:00, 287kB/s]
Type: Stories
Traceback (most recent call last):
  File "O:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "O:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "O:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "O:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "O:\OnlyFans-master\modules\onlyfans.py", line 786, in prepare_scraper
    highlight = await subscription.get_highlights(hightlight_id=highlight.id)
  File "O:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 273, in get_highlights
    results = [create_story(x) for x in results["stories"]]
TypeError: 'error_details' object is not subscriptable`

Just had the same error with a model I am in a paid subscription to
