### ISSUE TITLE
TypeError: object list can't be used in 'await' expression

### ISSUE THREAD

**Issue by froppster** [DIGITALCRIMINAL/UltimaScraper#1518]
Hello,

I'm hoping to get some help with an error that I'm receiving. I used the scraper last month at some point without issue. Today, I pulled the repo, ran pip install --upgrade --user -r requirements.txt, and updated auth.json. Now, when I try to run the script, I get the output that I've included below. Is there possibly a config problem on my end? Please let me know if I can provide any info to assist.

```
Site: 0 = onlyfans |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Welcome [user] | [user]
Scraping Paid Content
Scraping - [sub1] | 1 / 1
Scraping Subscriptions
Names: Username = username  | 0 = All | 1 = [sub1]
1
Scrape Processing
Name: [sub1]
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
2
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Processing Scraped Posts
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\repos\git\DC-OF\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\repos\git\DC-OF\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\repos\git\DC-OF\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\repos\git\DC-OF\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\repos\git\DC-OF\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\repos\git\DC-OF\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "C:\Users\[UserName]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\[UserName]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\[UserName]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression
```

**Comment by fractalhelios** [comment]
i have the same issue.

**Comment by MrRawrrino89** [comment]
Yeah same problem here also.

**Comment by J4k-The-Reaper** [comment]
yepperz. i believe everyone does. dont worry, be patient. it will be fixed in due time. DC is doing their best, in due time.

**Comment by kittiess** [comment]
Having the same issue.

**Comment by Qwertyx211** [comment]
Same as well

**Comment by rhklzb** [comment]
I found a quick workaround: in `requirements.txt` replace line 14 (https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/requirements.txt#L14) with
```
tqdm==4.59.0
```
rebuild the docker image (if using it) or reinstall the requirements and you should be good to go.

**Comment by Paulchen1409** [comment]
> I found a quick workaround: in `requirements.txt` replace line 14 (https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/requirements.txt#L14) with
> 
> ```
> tqdm==4.59.0
> ```
> 
> rebuild the docker image (if using it) or reinstall the requirements and you should be good to go.

Tested that for myself, works flawlessly now!

**Comment by MrRawrrino89** [comment]
> > I found a quick workaround: in `requirements.txt` replace line 14 (https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/requirements.txt#L14) with
> > ```
> > tqdm==4.59.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > rebuild the docker image (if using it) or reinstall the requirements and you should be good to go.
> 
> Tested that for myself, works flawlessly now!

yeah works for me also! appreciated!

**Comment by J4k-The-Reaper** [comment]
> I found a quick workaround: in `requirements.txt` replace line 14 (https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/requirements.txt#L14) with
> ```
> tqdm==4.59.0
> ```
> rebuild the docker image (if using it) or reinstall the requirements and you should be good to go.

Yezzer! Works like a charm. Knew there were smarter folks out there than me!

**Comment by Filican** [comment]
> I found a quick workaround: in `requirements.txt` replace line 14 (https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/requirements.txt#L14) with
> 
> ```
> tqdm==4.59.0
> ```
> 
> rebuild the docker image (if using it) or reinstall the requirements and you should be good to go.

Hmm I tried doing this but still come up with the same error 

 ```
 File "D:\stuff\Folders\Site Rippers\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\stuff\Folders\Site Rippers\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\stuff\Folders\Site Rippers\OnlyFans-master\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "D:\stuff\Folders\Site Rippers\OnlyFans-master\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "C:\Users\[User]\\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\[User]\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression


```

**Comment by bigz140** [comment]
> I found a quick workaround: in `requirements.txt` replace line 14 (https://github.com/DIGITALCRIMINAL/OnlyFans/blob/master/requirements.txt#L14) with
> 
> ```
> tqdm==4.59.0
> ```
> 
> rebuild the docker image (if using it) or reinstall the requirements and you should be good to go.

Great, It's works. After 2 days confused. Thank you for your help.

**Comment by qtv** [comment]
tqdm==4.61.2 works for me and makes it work with python 3.10 as well

**Comment by PurpleDrank21** [comment]
tqdm==4.61.2 works for me as well

**Comment by undacovabrutha** [comment]
How do you "rebuild the docker image (if using it) or reinstall the requirements"...???
