### ISSUE TITLE
No more working: Names: Username = username  | 0 = All

### ISSUE THREAD

**Issue by seraph1976** [DIGITALCRIMINAL/UltimaScraper#1540]
Scrape all user with parameter 0 no more working:

Scrape Attempt: 1/100
Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by Jakeyy22** [comment]
Option 0 does still work. You just have this issue with a certain creator, which is causing the fail.

I currently have it with 2 creators, so I'm running the creators manually, so I know which fail and work.

**Comment by americanseeder1865** [comment]
The key error is in [create_post.py](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/f077e30d8312a10aa2fe576864f37c1d7a1df5e3/apis/onlyfans/classes/create_post.py#L1) because it doesn't exist in [create_user.py](https://github.com/DIGITALCRIMINAL/OnlyFans/blob/f077e30d8312a10aa2fe576864f37c1d7a1df5e3/apis/onlyfans/classes/create_post.py#L13) . Based on the code, I wonder if OnlyFans didn't update something in their response header to now include "author". It has two values (from my bad understanding of this), "id" and "_view". 

Same issue as #1538 

Photo of what I am talking about below this
 #-------------------------------------------------
![Capture - Copy](https://user-images.githubusercontent.com/87628702/128493348-424e2ac2-875a-4ab0-aefe-21ab59f13b19.PNG)

**Comment by lucky1luc** [comment]
same problem with one author

**Comment by naodrej** [comment]
Try this
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231

**Comment by americanseeder1865** [comment]
> Try this
> [#1419 (comment)](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231)

This Works. What does it do?
