### ISSUE TITLE
Error Handling is Missing 

### ISSUE THREAD

**Issue by pnpninja** [DIGITALCRIMINAL/UltimaScraper#1543]
Messages was blocked by a content creator but still subscribed. Caused error to be thrown. Please handle it

`Traceback (most recent call last):
  File "/Volumes/The Dojo/Torrent/OnlyFans/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/Users/prateek/opt/anaconda3/envs/OF39/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Volumes/The Dojo/Torrent/OnlyFans/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/Volumes/The Dojo/Torrent/OnlyFans/datascraper/main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "/Volumes/The Dojo/Torrent/OnlyFans/helpers/main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/Volumes/The Dojo/Torrent/OnlyFans/modules/onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/Volumes/The Dojo/Torrent/OnlyFans/modules/onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "/Volumes/The Dojo/Torrent/OnlyFans/apis/onlyfans/classes/create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "/Volumes/The Dojo/Torrent/OnlyFans/apis/onlyfans/classes/create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "/Volumes/The Dojo/Torrent/OnlyFans/apis/onlyfans/classes/create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'`

**Comment by Jakeyy22** [comment]
Same issue as #1538 #1540 

An easy fix for now has been posted on #1419
