### ISSUE TITLE
I get this particular issue when selecting OF as a website in cmd

### ISSUE THREAD

**Issue by pashata777** [DIGITALCRIMINAL/UltimaScraper#1554]
Traceback (most recent call last):
  File "F:\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\vlado\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\OnlyFans-7.4.1\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\OnlyFans-7.4.1\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "F:\OnlyFans-7.4.1\OnlyFans-7.4.1\helpers\main_helper.py", line 910, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Unexpected character in found when decoding object value

**Comment by Alilawa12** [comment]
choni mama amnasi?

**Comment by LunarPenguin** [comment]
Make sure the `auth.json` is valid json. It seems to have trouble loading the auth details

**Comment by pashata777** [comment]
everything is valid, still not working

**Comment by titiagomei** [comment]
did you ever get it to work?
