### ISSUE TITLE
Traceback (most recent call last): error

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINAL/UltimaScraper#1574]
Traceback (most recent call last):
  File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\lopefgth\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Temp\OnlyFans DataScraper v7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\Temp\OnlyFans DataScraper v7.4.1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Temp\OnlyFans DataScraper v7.4.1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Temp\OnlyFans DataScraper v7.4.1\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "C:\Temp\OnlyFans DataScraper v7.4.1\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "C:\Temp\OnlyFans DataScraper v7.4.1\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "C:\Temp\OnlyFans DataScraper v7.4.1\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by xxx-uploaded** [comment]
link working script
https://github.com/kozobot/OnlyFans

**Comment by Fall0n** [comment]
> link working script
> https://github.com/kozobot/OnlyFans

give me same error. Not working link script do i think talking aboute

**Comment by horatiorosa** [comment]
y'all might want to try this workaround [#1419 (comment)](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231)

**Comment by americanseeder1865** [comment]
He fixed it. [Reinstall using this repo](https://github.com/DIGITALCRIMINALS/OnlyFans)
