### ISSUE TITLE
Str has no attribute get

### ISSUE THREAD

**Issue by Eviepayne** [DIGITALCRIMINAL/UltimaScraper#1615]
```
$ docker exec -it 8308566ebe46 python --version
Python 3.9.5
```
This is the stack trace I get. Using docker for python.
Only happens with some models.
```
Traceback (most recent call last):
  File "/usr/src/app/./start_ofd.py", line 44, in <module>
    api = main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/usr/src/app/datascraper/main_datascraper.py", line 105, in start_datascraper
    names = main_helper.process_names(
  File "/usr/src/app/helpers/main_helper.py", line 641, in process_names
    result = module.start_datascraper(
  File "/usr/src/app/modules/onlyfans.py", line 159, in start_datascraper
    results = prepare_scraper(authed, site_name, item)
  File "/usr/src/app/modules/onlyfans.py", line 756, in prepare_scraper
    master_set = subscription.get_posts()
  File "/usr/src/app/apis/onlyfans/classes/create_user.py", line 295, in get_posts
    final_results = [create_post(x, self.session_manager) for x in results]
  File "/usr/src/app/apis/onlyfans/classes/create_user.py", line 295, in <listcomp>
    final_results = [create_post(x, self.session_manager) for x in results]
  File "/usr/src/app/apis/onlyfans/classes/create_post.py", line 10, in __init__
    self.responseType: str = option.get("responseType")
AttributeError: 'str' object has no attribute 'get'
```

**Comment by LunarPenguin** [comment]
it seems like a connection error to me, i would suggest to try again to see if it resolved itself
