### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by Just-Chakal** [DIGITALCRIMINAL/UltimaScraper#1626]
I've got this error when, i execute

Site: 0 = onlyfans |

Traceback (most recent call last):
  File "C:\Users\Chakal\Desktop\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Chakal\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Chakal\Desktop\OnlyFans-master\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

**Comment by americanseeder1865** [comment]
Can you give me some info on how to recreate this?

**Comment by Chakal-1337** [comment]
> Can you give me some info on how to recreate this?

That ok I solve this problem, it work.

**Comment by americanseeder1865** [comment]
Awesome! Would you mind closing this issue?

**Comment by Chakal-1337** [comment]
> Awesome! Would you mind closing this issue?

ye thx again

**Comment by shaypi** [comment]
> > Can you give me some info on how to recreate this?
> 
> That ok I solve this problem, it work.

How do you manage to solve it?
