### ISSUE TITLE
Cant scrape certain profile.

### ISSUE THREAD

**Issue by RonnieBlaze** [DIGITALCRIMINAL/UltimaScraper#1659]
I follow sarah_fong and her free profile.  Every time i try to scrape hers the script errors with this.

Scrape Processing
Name: sarah_fong
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
  0%|                                                                                                                                                                                          | 0/61 [00:00<?, ?it/s]Traceback (most recent call last):
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Ronnie\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
  File "C:\Users\Ronnie\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Ronnie\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\Ronnie\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\Ronnie\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\modules\onlyfans.py", line 1136, in media_scraper
    matches = [s for s in ignored_keywords if s in final_text]
  File "F:\Users\xxx\Downloads\OnlyFans-7.4.3\modules\onlyfans.py", line 1136, in <listcomp>
    matches = [s for s in ignored_keywords if s in final_text]
TypeError: argument of type 'NoneType' is not iterable

It use to scrape just fine a couple months ago.

**Comment by direttc** [comment]
I have the same issue. This workaround [#issuecomment-893816231](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) fixed it.

**Comment by RonnieBlaze** [comment]
I did that fix, it worked for some but this one profile still errors.

**Comment by Nypheena** [comment]
> I have the same issue. This workaround [#issuecomment-893816231](https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1419#issuecomment-893816231) fixed it.

I tried that I still get this even with profiles that used to work
