### ISSUE TITLE
Get this error.. Is a update on the way?

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINAL/UltimaScraper#1669]
File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\*******\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Temp\OnlyFans DataScraper v7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "C:\Temp\OnlyFans DataScraper v7.4.1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Temp\OnlyFans DataScraper v7.4.1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Temp\OnlyFans DataScraper v7.4.1\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "C:\Temp\OnlyFans DataScraper v7.4.1\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "C:\Temp\OnlyFans DataScraper v7.4.1\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "C:\Temp\OnlyFans DataScraper v7.4.1\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by techbot2342** [comment]
Getting the same thing

**Comment by brianclogan** [comment]
When you get to the point where it says `0 | onlyfans`, enter `0`, then hit enter. That fixed it for me. It doesn't default to 0 anymore.

**Comment by Fall0n** [comment]
> When you get to the point where it says `0 = onlyfans`, enter `0`, then hit enter. That fixed it for me. It doesn't default to 0 anymore.

That the way i have done it all the time.. If i just hit enter i get this error


Traceback (most recent call last):
  File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Chrille NUC\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

**Comment by brianclogan** [comment]
strange, when entering 0 it runs the script on my side. I am running it in docker, brand new instance and it works fine.

**Comment by Fall0n** [comment]
> strange, when entering 0 it runs the script on my side. I am running it in docker, brand new instance and it works fine.

Very odd it work for you

Have try on 2 other pc same error win 10 is installed on all 3 pc

**Comment by jeff-geoff** [comment]
I get this on one particular model, the rest of the script runs fine.
