### ISSUE TITLE
sqlalchemy error

### ISSUE THREAD

**Issue by JarekLB** [DIGITALCRIMINAL/UltimaScraper#1677]
When first trying to setup the program after running the command "python3 start_ofd.py" I get the following.

I do in fact have the lastest version of Sqalchemy installed so im not sure why its giving me this error

Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\OnlyFans-master\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\xxx\Desktop\OnlyFans-master\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\xxx\Desktop\OnlyFans-master\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "C:\Users\xxx\Desktop\OnlyFans-master\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by LunarPenguin** [comment]
- check to see if you perhaps have multiple versions of python installed.
- check if `SQLAlchemy` is installed for the version of python your using to run the scraper
- When installing the `SQLAlchemy` module check if the spelling for the module is correct

**Comment by oz-richardson-reclique** [comment]
Could it be that the actual module is "SQLAlchemy" instead of "sqlalchemy"?
I'm having the same problem.

**Comment by alexey-romero** [comment]
I don't think it's case sensitive
