### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by developedbyalex** [DIGITALCRIMINAL/UltimaScraper#1681]
Traceback (most recent call last):
  File "E:\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\alexp\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 48, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "E:\OnlyFans-7.4.1\helpers\main_helper.py", line 915, in process_profiles
    auth = api.add_auth(json_auth)
  File "E:\OnlyFans-7.4.1\apis\onlyfans\onlyfans.py", line 45, in add_auth
    temp_auth_details = auth_details(options).upgrade_legacy(options)
  File "E:\OnlyFans-7.4.1\apis\onlyfans\classes\extras.py", line 9, in __init__
    self.cookie = cookie_parser(options.get("cookie", ""))
  File "E:\OnlyFans-7.4.1\apis\onlyfans\classes\extras.py", line 62, in __init__
    key, value = crumble.strip().split("=")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by LunarPenguin** [comment]
this seems to be a problem with the parsing of the cookies you supplied in the `auth.json` file. make sure to paste them in without the `Cookie:` prefix.

If you want to supply a (redacted) version of your `auth.json` file i can have a look to see if i can spot the problem.
