### ISSUE TITLE
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):   File "C:\Users\<MYUSER>a\Downloads\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>     loop.run_until_complete(main())   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete     return future.result()

### ISSUE THREAD

**Issue by s0l0b1t** [DIGITALCRIMINAL/UltimaScraper#1684]
0%|                                                                                            | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\<MYUSER>a\Downloads\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\<MYUSER>a\Downloads\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\<MYUSER>a\Downloads\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 90, in start_datascraper
    await module.paid_content_scraper(api, identifiers)
  File "C:\Users\<MYUSER>a\Downloads\OnlyFans-7.4.1\modules\onlyfans.py", line 401, in paid_content_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "C:\Users\<MYUSER>a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\<MYUSER>a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\<MYUSER>a\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression

**Using email/pass login, auth is successful. On scrape it returns ^ this error.

**Comment by Oneill1995** [comment]
I had a similar issue. Look to see if the sess in the auth file is correct

**Comment by Avisz** [comment]
> I had a similar issue. Look to see if the sess in the auth file is correct

i have the same error , did you solve it ?

**Comment by Oneill1995** [comment]
> > I had a similar issue. Look to see if the sess in the auth file is correct
> 
> i have the same error , did you solve it ?

Yes, you should just need to recheck all the values in the auth.json file, especially sess which was different from when I last used it. That's what worked for me at least

**Comment by Avisz** [comment]
> Yes, you should just need to recheck all the values in the auth.json file, especially sess which was different from when I last used it. That's what worked for me at least

yeah i rechecked every value , i get the error when it starts scrapping 
i will provide a screenshot
tried with multiple models its the same error
https://i.imgur.com/MlkWiwC.png

**Comment by IT6uru** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans

fixed here

**Comment by LunarPenguin** [comment]
It seems to be a problem with the `tqdm` module. try up-/downgrading the `tqdm` module to see if that has any effect.

Also could you please rename the issue to a shorter more descriptive name.

**Comment by goodboi2** [comment]
I am getting this issue. I've tried every suggestion here and it's not working.

![Screenshot 2021-09-18 081909](https://user-images.githubusercontent.com/90967866/133888616-85f43ffc-de01-4119-a3a5-223209aca01e.jpg)

**Comment by DIGITALCRIMINALS** [comment]
Click on my username and use my fork

**Comment by goodboi2** [comment]
> 
> 
> Click on my username and use my fork

I am still getting this error using your fork.

**Comment by goodboi2** [comment]
Does anyone have a fix for this? I have tried 7.4.3 and 7.4.4 of the fork given above.
