### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by patsypats** [DIGITALCRIMINAL/UltimaScraper#1687]
Traceback (most recent call last):
  File "H:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "H:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "H:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "H:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "H:\OnlyFans-master\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "H:\OnlyFans-master\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
TypeError: gather() takes 2 positional arguments but 319 were given

I have checked my auth file.

**Comment by thegooch69** [comment]
Having exact same issue with identical error notes.

**Comment by blacknwhite98** [comment]
traceback (most recent call last):
  File "D:\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "D:\OnlyFans-7.4.1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "D:\OnlyFans-7.4.1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "D:\OnlyFans-7.4.1\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(tasks, **settings)
  File "C:\Users\XXXX\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in gather
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\XXXX\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 79, in <listcomp>
    res = [await f for f in cls.as_completed(ifs, loop=loop, timeout=timeout,
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 614, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\XXXXX\AppData\Roaming\Python\Python39\site-packages\tqdm\asyncio.py", line 76, in wrap_awaitable
    return i, await f
TypeError: object list can't be used in 'await' expression

**Comment by IT6uru** [comment]
https://github.com/DIGITALCRIMINALS/OnlyFans

Fixed here

**Comment by patsypats** [comment]
The fix is not published there.

**Comment by vfrxart** [comment]
> 
> 
> The fix is not published there.

it is the fix. you have to use version 7.4.3 on that page, it's different to the one listed in this repo. works just fine

**Comment by LunarPenguin** [comment]
This might have something to do with the newest version of `tqdm` not being stable enough. consider downgrading to a lower version of `tqdm` to see if that fixes the problem.

**Comment by goodboi2** [comment]
> 
> 
> https://github.com/DIGITALCRIMINALS/OnlyFans
> 
> Fixed here
> 
> 
> > The fix is not published there.
> 
> it is the fix. you have to use version 7.4.3 on that page, it's different to the one listed in this repo. works just fine

This does not work
