### ISSUE TITLE
Unable to find set of matching capabilities

### ISSUE THREAD

**Issue by TokenGX-dev** [DIGITALCRIMINAL/UltimaScraper#1689]
I keep getting this error when attempting to auth. I have updated to the latest version of the ripper, and downloaded geckodriver on prompt. I double, triple, quadruple checked my auth.json and my settings.json files. Can anyone help me figure this out?

Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "..\OnlyFans rips\OnlyFans-master\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "..\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "..\OnlyFans rips\OnlyFans-master\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "..\OnlyFans rips\OnlyFans-master\OnlyFans\datascraper\main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "..\OnlyFans rips\OnlyFans-master\OnlyFans\modules\onlyfans.py", line 116, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "..\OnlyFans rips\OnlyFans-master\OnlyFans\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "..\OnlyFans rips\OnlyFans-master\OnlyFans\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "..\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by LunarPenguin** [comment]
This seems to be a selenium issue rather than a OF-scraper problem. 

A quick google search seems to suggest upgrading either selenium or Firefox or both.

If you can provide an extract from your `auth` file i can have a look at it to see if it is configured properly
