### ISSUE TITLE
Failed while scraping

### ISSUE THREAD

**Issue by developedbyalex** [DIGITALCRIMINAL/UltimaScraper#1695]
Traceback (most recent call last):
  File "E:\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\alexp\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "E:\OnlyFans-7.4.1\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "E:\OnlyFans-7.4.1\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "E:\OnlyFans-7.4.1\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "E:\OnlyFans-7.4.1\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "E:\OnlyFans-7.4.1\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "E:\OnlyFans-7.4.1\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by 0x000NULL** [comment]
I get same issue. Exact same stack trace. Win 10, Python 3.9.5

**Comment by LunarPenguin** [comment]
there currently is a workaround for this problem that works for most people. Look here #1588 and here #1419

**Comment by goodboi2** [comment]
> 
> 
> there currently is a workaround for this problem that works for most people. Look here #1588 and here #1419

Those do not work for me and I am having the same issue on all forks and versions.
