### ISSUE TITLE
error when trying to download videos

### ISSUE THREAD

**Issue by lemonpillow** [DIGITALCRIMINAL/UltimaScraper#1699]
Traceback (most recent call last):
  File "C:\Users\.\Desktop\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\.\Desktop\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\.\Desktop\OnlyFans\datascraper\main_datascraper.py", line 95, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\.\Desktop\OnlyFans\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\.\Desktop\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\.\Desktop\OnlyFans\modules\onlyfans.py", line 840, in prepare_scraper
    await process_metadata(
  File "C:\Users\.\Desktop\OnlyFans\modules\onlyfans.py", line 664, in process_metadata
    result = main_helper.export_sqlite(archive_path, api_type, new_metadata_object)
  File "C:\Users\.\Desktop\OnlyFans\helpers\main_helper.py", line 583, in export_sqlite
    created_at = media["created_at"]
KeyError: 'created_at'

**Comment by goodboi2** [comment]
I've been getting this error on the latest version and the forks of it and I can't get it to work.
