### ISSUE TITLE
Only in one user script stop 

### ISSUE THREAD

**Issue by jerryhard** [DIGITALCRIMINAL/UltimaScraper#1702]
crape Processing
Name: demisutra
Scrape: 0 = All | 1 = Images | 2 = Videos | 3 = Audios | 4 = Texts
0
Type: Profile
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Traceback (most recent call last):
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/./start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/./start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/datascraper/main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/helpers/main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/modules/onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/modules/onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/apis/onlyfans/classes/create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/apis/onlyfans/classes/create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "/ontap/Pic/Patreon_kurvicky/DOWNLOAD/DC/OnlyFans/apis/onlyfans/classes/create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'

**Comment by StiffPP** [comment]
Type: Profile
100%|█████████████████████████████████████████████████████████████████████████████| 2.53M/2.53M [00:00<00:00, 3.04MB/s]
Type: Stories
No Stories Found.
Type: Posts
Scrape Attempt: 1/100
Type: Archived Posts
Scrape Attempt: 1/100
Processing Scraped Posts
Traceback (most recent call last):
  File "C:\Users\Deez Nutz\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Deez Nutz\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\Deez Nutz\OnlyFans\datascraper\main_datascraper.py", line 95, in start_datascraper
    await main_helper.process_names(
  File "C:\Users\Deez Nutz\OnlyFans\helpers\main_helper.py", line 940, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "C:\Users\Deez Nutz\OnlyFans\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "C:\Users\Deez Nutz\OnlyFans\modules\onlyfans.py", line 823, in prepare_scraper
    unrefined_set = await tqdm.gather(*tasks, **settings)
TypeError: gather() takes 2 positional arguments but 765 were given


I got the same error, hoping for a fix!
