### ISSUE TITLE
Traceback error on latest version

### ISSUE THREAD

**Issue by jimmothy-beep** [DIGITALCRIMINAL/UltimaScraper#1771]
hey all,

does anyone have a fix for this?
`Traceback (most recent call last):
  File "E:\OnlyFans-master\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\XX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\OnlyFans-master\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "E:\OnlyFans-master\datascraper\main_datascraper.py", line 93, in start_datascraper
    await main_helper.process_names(
  File "E:\OnlyFans-master\helpers\main_helper.py", line 939, in process_names
    result = await module.start_datascraper(authed, username, site_name)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 160, in start_datascraper
    await prepare_scraper(authed, site_name, item)
  File "E:\OnlyFans-master\modules\onlyfans.py", line 791, in prepare_scraper
    master_set = await subscription.get_posts()
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in get_posts
    final_results = [create_post(x, self) for x in results]
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_user.py", line 301, in <listcomp>
    final_results = [create_post(x, self) for x in results]
  File "E:\OnlyFans-master\apis\onlyfans\classes\create_post.py", line 13, in __init__
    self.author = create_user.create_user(option["author"])
KeyError: 'author'`

**Comment by djmarioka** [comment]
I'm having the same error, could you fix it?. Thanks.

**Comment by sxrzme** [comment]
I have a problem too

**Comment by docholllidae** [comment]
the author lost access to his account, or this repo?
anyway, he moved his repo to and maintains it here https://github.com/DIGITALCRIMINALS/OnlyFans  (notice the S added to the end of his name)
