### ISSUE TITLE
Help me with this code pls

### ISSUE THREAD

**Issue by Alexo88** [DIGITALCRIMINAL/UltimaScraper#1804]
I dont know what means this 

Traceback (most recent call last):
  File "C:\Users\Nerv\Desktop\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Nerv\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Nerv\Desktop\OnlyFans-7.4.1\start_ofd.py", line 41, in main
    site_choice = int(site_choice)
ValueError: invalid literal for int() with base 10: ''

**Comment by lgtb283** [comment]
I'm getting the same thing. Can someone help?

**Comment by GuimFreitas** [comment]
The application is bugged and neither has a video tutorial for installation, nor an integration for Chrome. I advice you to use a OnlyFans Stalker.
