### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by superfan12345** [DIGITALCRIMINAL/UltimaScraper#1807]
Traceback (most recent call last):
  File "C:\Users\123\Desktop\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.496.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\123\Desktop\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\123\Desktop\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "C:\Users\123\Desktop\OnlyFans-7.6.1\helpers\main_helper.py", line 937, in process_profiles
    temp_json_auth = ujson.load(open(user_auth_filepath))
ValueError: Expected object or value

**Comment by superfan12345** [comment]
hopefully someone knows a fix

**Comment by savagediver** [comment]
Hi @superfan12345 . Check your profile.json file carefully. `load` method does not got what its expects.

**Comment by superfan12345** [comment]
anyone?

**Comment by End3r-Duty** [comment]
bump

**Comment by superfan12345** [comment]
already fixed myself.

**Comment by 154pinkchairs** [comment]
@superfan12345 how?

**Comment by xanax-atr** [comment]
> already fixed myself.

How did you fix this error?
