### ISSUE TITLE
Auth 404'ed

### ISSUE THREAD

**Issue by nomimani** [DIGITALCRIMINAL/UltimaScraper#1833]
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Auth 404'ed
Auth (V1) Attempt 2/10
Auth 404'ed
Auth (V1) Attempt 3/10
Auth 404'ed
Auth (V1) Attempt 4/10
Auth 404'ed
Auth (V1) Attempt 5/10
Auth 404'ed
Auth (V1) Attempt 6/10
Auth 404'ed
Auth (V1) Attempt 7/10
Auth 404'ed
Auth (V1) Attempt 8/10
Auth 404'ed
Auth (V1) Attempt 9/10
Auth 404'ed
Auth (V1) Attempt 10/10
Auth 404'ed
Traceback (most recent call last):
  File "/home/office/Desktop/OnlyFans-master/start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/office/Desktop/OnlyFans-master/start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "/home/office/Desktop/OnlyFans-master/datascraper/main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/home/office/Desktop/OnlyFans-master/modules/onlyfans.py", line 87, in account_setup
    authed = await auth.login()
  File "/home/office/Desktop/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 132, in login
    user = await self.get_user(auth_id)
  File "/home/office/Desktop/OnlyFans-master/apis/onlyfans/classes/create_auth.py", line 194, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

**Comment by nomimani** [comment]
I also tried sudo /Applications/Python\ 3.9/Install\ Certificates.command
sudo: /Applications/Python 3.9/Install Certificates.command: command not found

**Comment by jaysomm** [comment]
I had to fill in a new cookie in am updated .auth file: x-bc. 

Also im curious as to what that cookie is, if anyone can explain?

**Comment by vvglyy** [comment]
Not working for me, adding line x-bc

**Comment by robwri35** [comment]
Hi, Getting the same error, did anyone manage to sort it?
