### ISSUE TITLE
need help.

### ISSUE THREAD

**Issue by Kimantonsson** [DIGITALCRIMINAL/UltimaScraper#1839]
Traceback (most recent call last):
  File "C:\Temp\OnlyFans DataScraper v7.4.1\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Temp\OnlyFans DataScraper v7.4.1\tests\main_test.py", line 24, in check_config
    json_config, updated = main_helper.get_config(path)
  File "C:\Temp\OnlyFans DataScraper v7.4.1\helpers\main_helper.py", line 812, in get_config
    json.dumps(make_settings.config(**json_config), default=lambda o: o.__dict__)
  File "C:\Temp\OnlyFans DataScraper v7.4.1\classes\make_settings.py", line 249, in __init__
    self.supported = Supported(**supported)
TypeError: __init__() got an unexpected keyword argument 'fansly'

see that some one use 7.6.1 and i only see 7.4.1 on webpage.. where can i fin new 7.6.1

**Comment by shixel** [comment]
Getting this same error.
