### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by luisalfredorr22** [DIGITALCRIMINAL/UltimaScraper#1845]
I don't know why I am getting this error, even though a configure the auth.json the same way you put in the instructions. As I don't know how to interpret the error, I'd like to ask if I am getting it because of a bad edition on the `auth.json`?

```
(onlyfans) C:\Users\pepito\Desktop\github_projects\OnlyFans>python updater.py   
Script has been updated, exiting in 5 seconds

(onlyfans) C:\Users\pepito\Desktop\github_projects\OnlyFans>
(onlyfans) C:\Users\pepito\Desktop\github_projects\OnlyFans>python start_ofd.py 
Site: 0 = onlyfans | 
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
0
Auth (V1) Attempt 1/10
Something went wrong. [BB91C8D6]
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "C:\Users\pepito\Desktop\github_projects\OnlyFans\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\pepito\anaconda3\envs\onlyfans\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\pepito\Desktop\github_projects\OnlyFans\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\pepito\Desktop\github_projects\OnlyFans\datascraper\main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\pepito\Desktop\github_projects\OnlyFans\modules\onlyfans.py", line 116, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "C:\Users\pepito\Desktop\github_projects\OnlyFans\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "C:\Users\pepito\Desktop\github_projects\OnlyFans\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "C:\Users\pepito\anaconda3\envs\onlyfans\lib\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\pepito\anaconda3\envs\onlyfans\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    self.service.start()
  File "C:\Users\pepito\anaconda3\envs\onlyfans\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Users\pepito\anaconda3\envs\onlyfans\lib\site-packages\selenium\webdriver\common\service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service C:\Users\pepito\Desktop\github_projects\OnlyFans\extras\OFLogin\geckodriver.exe unexpectedly exited. Status code was: 64
```

The auth.json file I used is the following:^

```
{
  "auth": {
    "username": "myusername",
    "cookie": "csrf=aaaaaaaaaaa; cookiesAccepted=true; auth_uid_bbbbbbbbbb=cccccccccccc;auth_uid_dddddddddddd=eeeeeeeeeee; fp=ffffff; auth_id=gggg;sess=hhhh; st=iiii",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0",
    "email": "xxxxxxx@gmail.com",
    "password": "yyyyyyyyy",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}
```

Please note that I put alphabet letters to not show sensitive information...

**Comment by Bulli** [comment]
Use this release: https://github.com/DIGITALCRIMINALS/OnlyFans/releases/tag/v7.6.1

**Comment by simonrule** [comment]
im having same issue

**Comment by aizenn1** [comment]
Email and Pass not required just let them empty, make sure to change the folder called default in ".profiles\OnlyFans" to your OF username, this might work fixed your issue

**Comment by EyassShahoud** [comment]
> Use this release: https://github.com/DIGITALCRIMINALS/OnlyFans/releases/tag/v7.6.1
> 
> Fill in: x-bc in auth.json Use python 3.10

you cant use python 3.10 becasue skript ask for 3.9
