### ISSUE TITLE
geckodriver.exe unexpectedly exited. Status code was: 64

### ISSUE THREAD

**Issue by Maj-ew** [DIGITALCRIMINAL/UltimaScraper#1865]
D:\OnlyFans-7.4.1>python start_ofd.py
Site: 0 = onlyfans |
0
Choose Profile
Names: Username = username  | 0 = All | 1 = default
1
Auth (V1) Attempt 1/10
Access denied.
Auth (V1) Attempt 2/10
Access denied.
Auth (V1) Attempt 3/10
Access denied.
Auth (V1) Attempt 4/10
Access denied.
Auth (V1) Attempt 5/10
Access denied.
Auth (V1) Attempt 6/10
Access denied.
Auth (V1) Attempt 7/10
Access denied.
Auth (V1) Attempt 8/10
Access denied.
Auth (V1) Attempt 9/10
Access denied.
Auth (V1) Attempt 10/10
Access denied.
Opening Browser
Traceback (most recent call last):
  File "D:\OnlyFans-7.4.1\start_ofd.py", line 60, in <module>
    loop.run_until_complete(main())
  File "C:\Users\Tomek\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\OnlyFans-7.4.1\start_ofd.py", line 44, in main
    api = await main_datascraper.start_datascraper(
  File "D:\OnlyFans-7.4.1\datascraper\main_datascraper.py", line 66, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "D:\OnlyFans-7.4.1\modules\onlyfans.py", line 116, in account_setup
    oflogin.login(auth, domain, auth.session_manager.get_proxy())
  File "D:\OnlyFans-7.4.1\extras\OFLogin\start_ofl.py", line 77, in login
    web_browser = launch_browser(
  File "D:\OnlyFans-7.4.1\extras\OFLogin\start_ofl.py", line 33, in launch_browser
    driver = webdriver.Firefox(firefox_profile=profile, executable_path=driver_path,
  File "C:\Users\Tomek\AppData\Roaming\Python\Python39\site-packages\seleniumwire\webdriver\browser.py", line 45, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Tomek\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 176, in __init__
    self.service.start()
  File "C:\Users\Tomek\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Users\Tomek\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\common\service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service D:\OnlyFans-7.4.1\extras\OFLogin\geckodriver.exe unexpectedly exited. Status code was: 64

**Comment by omphteliba** [comment]
same here
