### ISSUE TITLE
weird error when running for first time

### ISSUE THREAD

**Issue by bstar16** [DIGITALCRIMINAL/UltimaScraper#1884]
i have yet to be able to run this yet heres my error 

Traceback (most recent call last):
  File "C:\Users\REALBAD\Downloads\DIGITALCRIMINAL-OnlyFans-master\DIGITALCRIMINAL-OnlyFans-master\start_ofd.py", line 16, in <module>
    import datascraper.main_datascraper as main_datascraper
  File "C:\Users\REALBAD\Downloads\DIGITALCRIMINAL-OnlyFans-master\DIGITALCRIMINAL-OnlyFans-master\datascraper\main_datascraper.py", line 6, in <module>
    import modules.onlyfans as m_onlyfans
  File "C:\Users\REALBAD\Downloads\DIGITALCRIMINAL-OnlyFans-master\DIGITALCRIMINAL-OnlyFans-master\modules\onlyfans.py", line 14, in <module>
    import extras.OFLogin.start_ofl as oflogin
  File "C:\Users\REALBAD\Downloads\DIGITALCRIMINAL-OnlyFans-master\DIGITALCRIMINAL-OnlyFans-master\extras\OFLogin\start_ofl.py", line 2, in <module>
    from seleniumwire import webdriver
  File "C:\Users\REALBAD\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\webdriver\__init__.py", line 1, in <module>
    from selenium.webdriver import *  # noqa
AttributeError: module 'selenium.webdriver' has no attribute 'Opera'

**Comment by NathanIfinity** [comment]
having the exact same issue? ran the requirement file and everything seems to be up to date

**Comment by jitteryelliptical** [comment]
Downgrading Selenium worked for me, I just pushed it back to 4.0.0.

https://github.com/DIGITALCRIMINAL/OnlyFans/blob/d1a5f7112eb95145fbfa9a3c58e3a49d69cbd10a/requirements.txt#L15

to: `selenium==4.0.0` and then re-install requirements.

**Comment by FrostedJakezZ** [comment]
> > Downgrading Selenium worked for me, I just pushed it back to 4.0.0.
> > https://github.com/DIGITALCRIMINAL/OnlyFans/blob/d1a5f7112eb95145fbfa9a3c58e3a49d69cbd10a/requirements.txt#L15
> > 
> > to: `selenium==4.0.0` and then re-install requirements.
> 
> i ended using the most latest version of this on his new account and i haven't experienced any issues since i would recommend using the new one https://github.com/DIGITALCRIMINALS/OnlyFans

breh the new one though??? great calll. ive been stumped on the original onlyfans-master, google doesnt show there to be a onlyfans-master_2 when you google a of data scraper. and when i search digitalcriminal on google his new account isnt archived either or wasnt when i looked his user up youd think the s on digitalcriminals wouldnt be a huge deal to a search engine and relevant search terms would search for it with and without the plural form. so literally google hid the new version from me simply by negating the s from his user.. 

crazyyy about to try running _2 right now thanks for link i woulda never known
