### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by johnnyturbo87** [DIGITALCRIMINAL/UltimaScraper#1909]
Was working fine yesterday. Today I get this. Any suggestions? 

```
Traceback (most recent call last):
  File "C:\Users\johnn\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\johnn\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\johnn\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\johnn\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "L:\OnlyFans-7.6.1\start_ofd.py", line 104, in <module>
    asyncio.run(main())
  File "C:\Users\johnn\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\johnn\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "L:\OnlyFans-7.6.1\start_ofd.py", line 86, in main
    api = await main_datascraper.start_datascraper(
  File "L:\OnlyFans-7.6.1\datascraper\main_datascraper.py", line 49, in start_datascraper
    api = main_helper.process_profiles(json_settings, proxies, site_name, api)
  File "L:\OnlyFans-7.6.1\helpers\main_helper.py", line 942, in process_profiles
    auth = api.add_auth(json_auth)
  File "L:\OnlyFans-7.6.1\apis\onlyfans\onlyfans.py", line 42, in add_auth
    auth = create_auth(pool=self.pool, max_threads=self.max_threads)
  File "L:\OnlyFans-7.6.1\apis\onlyfans\classes\create_auth.py", line 44, in __init__
    self.session_manager = api_helper.session_manager(self, max_threads=max_threads)
  File "L:\OnlyFans-7.6.1\apis\api_helper.py", line 95, in __init__
    dynamic_rules = requests.get(dr_link).json()  # type: ignore
  File "C:\Users\johnn\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by meanjoep92** [comment]
It seems like everyone is having this problem right now, but it turns out that the "dynamic_rules_link" in the `.settings/config.js`on is broken. If you post this link [https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/84ca30c8e1df3f35c3ad58e340685f876c655542/onlyfans.json](url) in the variable then it should work.

**Comment by johnnyturbo87** [comment]
Just tried that and it is still the same.
