### ISSUE TITLE
KeyError: 'data' for all profiles

### ISSUE THREAD

**Issue by lowlevel80** [DIGITALCRIMINAL/UltimaScraper#1921]
I had this working last week but now I get this error on every profile??

Type: Stories
Traceback (most recent call last):
  File "/var/of/start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/var/of/start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "/var/of/datascraper/main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "/var/of/datascraper/main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "/var/of/helpers/main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "/var/of/modules/module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "/var/of/modules/module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "/var/of/modules/onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "/var/of/apis/onlyfans/classes/user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results["data"]]
KeyError: 'data'

**Comment by lowlevel80** [comment]
Fixed with change results["data"] to result["list"] as per previous post (that doesn't show up on google)

**Comment by bigz140** [comment]
> Fixed with change results["data"] to result["list"] as per previous post (that doesn't show up on google)

Thank you. This worked for me.

**Comment by LunarPenguin** [comment]
A quick reminder that this repo is dead/stale and if you want updates you should go [here](https://github.com/DIGITALCRIMINALS/OnlyFans)
