### ISSUE TITLE
ImportError: cannot import name 'FanslyAPI' from 'ultima_scraper_api.apis.fansly.fansly' [mac]

### ISSUE THREAD

**Issue by melbandera** [DIGITALCRIMINAL/UltimaScraper#1982]
full traceback:
```
Traceback (most recent call last):
  File "/Users/[melbandera]/projects/OnlyFans/start_us.py", line 22, in <module>
    main_test.check_start_up()
  File "/Users/[melbandera]/projects/OnlyFans/tests/main_test.py", line 21, in check_start_up
    from ultima_scraper_collection.managers.filesystem_manager import FilesystemManager
  File "/Users/[melbandera]/Library/Caches/pypoetry/virtualenvs/ultima-scraper--uSdOj7--py3.11/lib/python3.11/site-packages/ultima_scraper_collection/__init__.py", line 1, in <module>
    from ultima_scraper_collection.managers.datascraper_manager.datascrapers.fansly import (
  File "/Users/[melbandera]/Library/Caches/pypoetry/virtualenvs/ultima-scraper--uSdOj7--py3.11/lib/python3.11/site-packages/ultima_scraper_collection/managers/datascraper_manager/datascrapers/fansly.py", line 13, in <module>
    from ultima_scraper_api.apis.fansly.fansly import FanslyAPI
ImportError: cannot import name 'FanslyAPI' from 'ultima_scraper_api.apis.fansly.fansly' (/Users/[melbandera]/projects/OnlyFans/ultima_scraper_api/apis/fansly/fansly.py)
```

i get this when i run `poetry run python start_us.py`. up-to-date with master branch. 

`python3 updater.py` seems to run successfully:

```
╰─ python3 updater.py
Updating dependencies
Resolving dependencies... (0.6s)

Writing lock file

Package operations: 24 installs, 0 updates, 0 removals

  • Installing lxml (4.9.2)
  • Installing user-agent (0.1.10)
  • Installing alembic (1.10.2)
  • Installing appdirs (1.4.4)
  • Installing cssselect (1.2.0)
  • Installing importlib-metadata (6.1.0)
  • Installing psycopg2 (2.9.5)
  • Installing pyee (8.2.2)
  • Installing tqdm (4.65.0)
  • Installing ultima-scraper-api (0.1.4)
  • Installing websockets (10.4)
  • Installing bs4 (0.0.1)
  • Installing click (8.1.3)
  • Installing fake-useragent (1.1.3)
  • Installing parse (1.19.0)
  • Installing pathspec (0.11.1)
  • Installing platformdirs (3.1.1)
  • Installing pyppeteer (1.0.2)
  • Installing pyquery (2.0.0)
  • Installing ultima-scraper-collection (0.1.4)
  • Installing w3lib (2.1.1)
  • Installing black (22.12.0)
  • Installing requests-html (0.10.0)
  • Installing ultima-scraper-renamer (0.1.3)
Script has been updated, exiting in 5 seconds
```

**Comment by scottgit64** [comment]
python3 updater.py
Updating dependencies
Resolving dependencies... (0.6s)

Writing lock file

Package operations: 24 installs, 0 updates, 0 removals

  • Installing lxml (4.9.2)
  • Installing user-agent (0.1.10)
  • Installing alembic (1.10.2)
  • Installing appdirs (1.4.4)
  • Installing cssselect (1.2.0)
  • Installing importlib-metadata (6.1.0)
  • Installing psycopg2 (2.9.5)
  • Installing pyee (8.2.2)
  • Installing tqdm (4.65.0)
  • Installing ultima-scraper-api (0.1.4)
  • Installing websockets (10.4)
  • Installing bs4 (0.0.1)
  • Installing click (8.1.3)
  • Installing fake-useragent (1.1.3)
  • Installing parse (1.19.0)
  • Installing pathspec (0.11.1)
  • Installing platformdirs (3.1.1)
  • Installing pyppeteer (1.0.2)
  • Installing pyquery (2.0.0)
  • Installing ultima-scraper-collection (0.1.4)
  • Installing w3lib (2.1.1)
  • Installing black (22.12.0)
  • Installing requests-html (0.10.0)
  • Installing ultima-scraper-renamer (0.1.3)
Script has been updated, exiting in 5 seconds
