### ISSUE TITLE
I have this problem how i can fix?

### ISSUE THREAD

**Issue by TheOppaiDragon** [DIGITALCRIMINAL/UltimaScraper#1992]
Traceback (most recent call last):
  File "C:\Users\Issei Hyodo\Desktop\Davide\OnlyFans-7.4.1\start_ofd.py", line 12, in <module>
    main_test.check_config()
  File "C:\Users\Issei Hyodo\Desktop\Davide\OnlyFans-7.4.1\tests\main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "C:\Users\Issei Hyodo\Desktop\Davide\OnlyFans-7.4.1\helpers\main_helper.py", line 1, in <module>
    from database.databases.user_data.models.api_table import api_table
  File "C:\Users\Issei Hyodo\Desktop\Davide\OnlyFans-7.4.1\database\databases\user_data\models\api_table.py", line 6, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'

**Comment by fulanii** [comment]
do `pip install sqlalchemy`

**Comment by TheOppaiDragon** [comment]
yes thx fixed. to get paid content on profile have free subscription u know how to do?

**Comment by LunarPenguin** [comment]
Please see #1991 and no its not possible to download premium content if your not subscribed to that creator
