### ISSUE TITLE
can i help me please

### ISSUE THREAD

**Issue by BragnarXIX** [DIGITALCRIMINAL/UltimaScraper#2001]
Traceback (most recent call last):
  File "D:\Onlyfans Scraper\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Onlyfans Scraper\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "D:\Onlyfans Scraper\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "D:\Onlyfans Scraper\datascraper\main_datascraper.py", line 74, in default
    setup, subscriptions = await account_setup(
  File "D:\Onlyfans Scraper\helpers\main_helper.py", line 983, in account_setup
    authed = await auth.login()
  File "D:\Onlyfans Scraper\apis\onlyfans\classes\auth_model.py", line 161, in login
    user = await self.get_user(auth_id)
  File "D:\Onlyfans Scraper\apis\onlyfans\classes\auth_model.py", line 225, in get_user
    response["session_manager"] = self.session_manager
TypeError: 'NoneType' object does not support item assignment

**Comment by BlueCalex** [comment]
I can see Python310 my guess would be use Python 3.9 instead of 3.10 as it doesnt work on 3.10
